# Copyright (c) 2021 Target Brands, Inc. All rights reserved.
#
# Use of this source code is governed by the LICENSE file in this repository.

version: '3'

services:
  vault:
    image: vault:1.9.1
    container_name: vault
    command: server -dev
    networks:
      - vault
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: superSecretToken
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

networks:
  vault:
