# SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  vault:
    image: vault:1.11.4
    container_name: vault
    command: server -dev
    networks:
      - vault
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: superSecretToken
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

networks:
  vault:
