# name of the action
name: reviewdog

# trigger on pull_request events
on:
  pull_request:

# pipeline to execute
jobs:
  diff-review:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20@sha256:cfc9d1b07b1ef4f7a4571f0b60a99646a92ef76adb7d9943f4cb7b606c6554e2
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: "--config=.golangci.yml"
        fail_on_error: true
        filter_mode: diff_context
        reporter: github-pr-review

  full-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v4
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: "--config=.golangci.yml"
        fail_on_error: false
        filter_mode: nofilter
